config/routes.rb
Rails.application.routes.draw do
    root 'chat_rooms#index'
    devise_for :users, :controllers => {registrations: 'registrations'}
    resources :chat_rooms, only: [:index, :new, :create, :show]
    resources :messages, only: [:create]
end

app/models/chat_room.rb
class ChatRoom < ActiveRecord::Base
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :user
    belongs_to :chat_room


    def created_stamp
        created_at.strftime('%H:%M:%S %d %B %Y')
    end
end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable

    has_many :chat_rooms, dependent: :destroy
    has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
    before_action :authenticate_user!

    def index
        @chat_rooms = ChatRoom.all
    end

    def show
        @chat_room = ChatRoom.includes(:messages).find(params[:id])
    end

    def new
        @chat_room = ChatRoom.new
    end

    def create
        @chat_room = current_user.chat_rooms.build(chat_room_params)
        if @chat_room.save
            flash[:success] = 'Chat room added!'
            redirect_to chat_rooms_path
        else
            render 'new'
        end
    end

    private

    def chat_room_params
        params.require(:chat_room).permit(:title)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    def create
        @message = Message.new(message_params)

        respond_to do |format|
            if @message.save
                format.js
            else
                format.js { render nothing: true }
            end
        end
    end

    private

    def message_params
        params.require(:message).permit(Message.attribute_names)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private
    def sign_up_params
        params.require(:user).permit(:nickname, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, opts = {})
        opts[:alt] = user.nickname
        image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}?s=#{opts.delete(:size) { 40 }}",
                  opts
    end
end

app/views/chat_rooms/_chat_room.html.erb
<li><%= link_to "Enter #{chat_room.title} room", chat_room_path(chat_room) %></li>

app/views/chat_rooms/index.html.erb
<h1>Chat rooms</h1>

<p class="lead"><%= link_to 'New chat room', new_chat_room_path, class: 'btn btn-primary' %></p>

<ul>
    <%= render @chat_rooms %>
</ul>

app/views/chat_rooms/new.html.erb
<h1>Add chat room</h1>

<%= form_for @chat_room do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: 'form-control' %>
    </div>

    <%= f.submit "Add", class: 'btn btn-primary' %>
<% end %>

app/views/chat_rooms/show.html.erb
<h1><%= @chat_room.title %></h1>

<div id="messages">
    <%= render @chat_room.messages %>
</div>

<div id="message_form">
    <div class="my_nick"><%= current_user.nickname %></div>
    <%= form_for Message.new, remote: true do |f| %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.text_field :content, placeholder: '채팅을 하자!' %>
        <%= f.submit :submit, value: '확인', id: 'submit' %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>NewStudy</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield(:js_css) %>
    <%= csrf_meta_tags %>
</head>
<body>

<div class="navigation">
    <%= link_to 'TTochi Chat App', root_path, class: 'home' %>
    <% if user_signed_in? %>
        <%= link_to '로그아웃', destroy_user_session_path, method: :delete, class: 'session' %>
    <% else %>
        <%= link_to '로그인', new_user_session_path, class: 'session' %>
        <%= link_to '가입', new_user_registration_path, class: 'session' %>
    <% end %>
</div>

<%= yield %>

</body>
</html>

<body>

app/views/messages/_message.html.erb
<div class="card">
    <div class="card-block">
        <div class="row">
            <div class="col-md-1">
                <%= gravatar_for message.user %>
            </div>
            <div class="col-md-11">
                <p class="card-text">
                    <span class="text-muted"><%= message.user.nickname %> at <%= message.created_stamp %> says</span><br>
                    <%= message.content %>
                </p>
            </div>
        </div>
    </div>
</div>

app/views/messages/create.js.erb
var messages = $('#messages');

$('#message_form').find('input.content').val('');
messages.append('<%= j render @message %>');

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>